# 风险模型设置文件

ID: 'barra'

# 风险描述子
risk_descriptors: 'BARRA'
others: ['wind_level_1','float_mkt_value']

# 两个股票池(CU、ESTU)
CU: '全A'
ESTU:
  func: 'typical_add_latest_st'
  func_args:
    st_months: 12

# 风险描述子的横截面清洗
cross_section_operate:
  # 标准化
  standard:
    priority: 1
    descriptors: ['BETA','BLEV','BTOP','CETOP','CMRA','DASTD','DTOA','EGRLF','EGRO','EGRSF','EPFWD','ETOP',
    'HSIGMA','LNCAP','MLEV','RSTR','SGRO','STOA','STOQ','STOM']
    mean_weight: 'LNCAP'
    std_weight: ~
  # 产生非线性市值因子
  nonlineat_size:
    priority: 2
    size: 'LNCAP'
    new_name: 'NLSIZE'
  # 标准化
  standard:
    priority: 3
    descriptors: 'NLSIZE'
    mean_weight: 'LNCAP'
    std_weight: ~
  # 去极端值
  drop_outlier:
    priority: 4
    descriptors: ['BETA','BLEV','BTOP','CETOP','CMRA','DASTD','DTOA','EGRLF','EGRO','EGRSF','EPFWD','ETOP',
    'HSIGMA','LNCAP','MLEV','RSTR','SGRO','STOA','STOQ','STOM','NLSIZE']
    method: 'Barra'
  # 标准化
  standard:
    priority: 5
    descriptors: ['BETA','BLEV','BTOP','CETOP','CMRA','DASTD','DTOA','EGRLF','EGRO','EGRSF','EPFWD','ETOP',
    'HSIGMA','LNCAP','MLEV','RSTR','SGRO','STOA','STOQ','STOM','NLSIZE']
    mean_weight: 'LNCAP'
    std_weight: ~
  # 合并描述子
  merge:
    priority: 6
    descriptors: ['DASTD','CMRA','HSIGMA']
    new_factor: 'VOLATILITY'
    weight: [0.74, 0.16, 0.10]
  merge:
    priority: 7
    descriptors: ['STOA','STOQ','STOM']
    new_factor: 'LIQUIDITY'
  merge:
    priority: 8
    descriptors: ['EPFWD','CETOP','ETOP']
    new_factor: 'EARNING'
    weight: [0.68, 0.21, 0.11]
  merge:
    priority: 9
    descriptors: ['MLEV','DTOA','BLEV']
    new_factor: 'LEVERAGE'
    weight: [0.38, 0.35, 0.27]
  merge:
    priority: 10
    descriptors: ['EGRLF','EGRSF','EGRO','SGRO']
    new_factor: 'GROWTH'
    weight: [0.18, 0.11, 0.24, 0.47]
  # 标准化
  standard:
    priority: 11
    descriptors: ['VOLATILITY','LIQUIDITY','EARNING','LEVERAGE','GROWTH']
    mean_weight: 'LNCAP'
    std_weight: ~
  # 正交化
  orthogonalize:
    priority: 12
    dependent: 'VOLATILITY'
    independents: ['BETA','LNCAP']
  orthogonalize:
    priority: 13
    dependent: 'LIQUIDITY'
    independents: ['LNCAP']
  # 标准化
  standard:
    priority: 14
    descriptors: ['VOLATILITY','LIQUIDITY']
    mean_weight: 'LNCAP'
    std_weight: ~
  # 填充缺失值
  fillna_barra:
    priority: 15
    descriptors: ['BETA','RSTR','VOLATILITY','BTOP','LIQUIDITY','EARNING','GROWTH','LEVERAGE']
    classify: 'wind_level_1'
    refs: 'LNCAP'
  # 标准化
  standard:
    priority: 16
    descriptors: ['BETA','RSTR','VOLATILITY','BTOP','LIQUIDITY','EARNING','GROWTH','LEVERAGE','LNCAP','NLSIZE']
    mean_weight: 'LNCAP'
    std_weight: ~

# 存储信息
save_info:
  factor_to_save: ['BETA','RSTR','VOLATILITY','BTOP','LIQUIDITY','EARNING','GROWTH','LEVERAGE','LNCAP','NLSIZE']
  factor_save_path: '/barra/factors/'
  run_type: 'S'     # S：串行  M：并行
  split_length: 75  # 日期分割长度
  cpu_use: 4        # CPU使用数量




